version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.12-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-deps
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: yarn test
      - run:
          name: code-coverage
          command: yarn coveralls
      - run:
          name: semantic release
          command: npm run semantic-release || true
